---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-vantor
data:
  database: vantor
  user: james

---
apiVersion: v1
kind: Secret
metadata:
  name: sec-vantor
data:
  password: bXlwYTU1
  root_password: cjAwdHBhNTU=


---
apiVersion: v1
kind: Pod
metadata:
  labels:
    you: me
  name: carl
spec:
  containers:
    - name: db
      image: docker.io/library/mysql
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: cm-vantor
              key: user
              
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: cm-vantor
              key: database

        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sec-vantor
              key: password
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sec-vantor
              key: root_password

# oc create configmap cm-vantor --from-literal user=james --from-literal database=vantor --dry-run=client -o yaml
# oc create secret generic sec-vantor --from-literal password=mypa55 --from-literal root_password=r00tpa55 --dry-run=client -o yaml
