apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
spec:
  hard:
    limits.cpu: 200m
    limits.memory: 200M
    memory: 100M
    requests.cpu: 100m
status: {}
# oc create quota compute-quota --hard requests.cpu=100m,memory=100M,limits.cpu=100m,limits.memory=100M --dry-run=client -o yaml > compute-quota.yml
