apiVersion: k8s.ovn.org/v1
kind: ClusterUserDefinedNetwork
metadata:
  name: test-udn
spec:
  namespaceSelector:
    matchLabels:
      env: test
  network:
    topology: Layer2
    layer2:
      role: Primary
      subnets:
        - 182.0.0.0/16
      ipam:
        lifecycle: Persistent
