apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "dev-limits"
spec:
  limits:
    - type: "Pod"
      max:
        cpu: "40m"
        memory: "100Mi"
      min:
        cpu: "10m"
        memory: "20Mi"
 
    - type: "Container"
      max:
        cpu: "20m"
        memory: "50Mi"
      min:
        cpu: "10m"
        memory: "20Mi"
      default:
        cpu: "10m"
        memory: "20Mi"
      defaultRequest:
        cpu: "10m"
        memory: "20Mi"
 
    - type: openshift.io/Image
      max:
        storage: 1Gi
