---
apiVersion: v1
kind: Service
metadata:
  name: vantor-app
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.port }}
  selector:
    you: me
status:
  loadBalancer: {}
