apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yml
  - service.yml
  - route.yml

configMapGenerator:
- name: cm-vantor
  literals:
    - user=mark
    - database=vantor

secretGenerator:
- name: sec-vantor
  literals:
    - password=mypa55
    - root_password=r00tpa55
generatorOptions:
  disableNameSuffixHash: true
  labels:
    type: generated-disabled-suffix
  annotations:
    note: generated-disabled-suffix
